name: laji-pygeoapi-python-scripts
services:
  python_scripts:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pygeoapi-config.yml:/app/pygeoapi-config.yml
      - ./.env:/.env
      - ./catalogue.tinydb:/app/catalogue.tinydb
    networks:
      - pygeoapinet

networks:
  pygeoapinet:
    name: pygeoapi_network