server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
        - fi-FI
    cors: true
    pretty_print: true
    limits:
        default_items: 100
        max_items: 10000
    templates:
        path: custom/templates/
        static: static/
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: FinBIF occurrence data OGC API
            fi: Lajitietokeskuksen havaintoaineistojen OGC API -rajapinta
        description:
            en: Latest update 2024-11-18. 
            fi: Päivitetty 2024-11-18.            
        keywords:
            en:
                - occurrence data
                - geospatial data
                - api
            fi:
                - lajitieto
                - paikkatieto
                - rajapinta
        keywords_type: place
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://info.laji.fi/en/frontpage/finnish-biodiversity-information-facility-finbif/terms-of-services/
        properties: 
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Luomus
        url: https://laji.fi/
    contact:
        name: Alpo, Turunen
        position: 
            en: Spatial Data Specialist
            fi: Paikkatietoasiantuntija
        address: Pohjoinen Rautatiekatu 13 
        city: Helsinki
        stateorprovince: Uusimaa
        postalcode: FI-00100
        phone:
        fax:
        instructions:
        hours:
        country: 
            en: Finland
            fi: Suomi
        email: alpo.turunen@helsinki.fi
        url: 
            en: https://laji.fi/en
            fi: https://laji.fi/
        role: pointOfContact

resources:

    occurrence-metadata:
        type: collection
        title: Occurrence Metadata 
        description: This metadata record contains metadata of the all collections in this service 
        keywords:
            en:
                - metadata
                - record
        extents:
            spatial:
                bbox: [19.08317359,59.45414258,31.58672881,70.09229553]
                crs: https://www.opengis.net/def/crs/EPSG/0/3067
            temporal: 
                begin: 1990-01-01T00:00:00Z
                end: 2024-09-18T00:00:00Z
        providers:
          - type: record
            name: TinyDBCatalogue
            data: catalogue.tinydb
            id_field: externalId
            time_field: recordCreated
            title_field: title
    