server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
        - fi-FI
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: FinBIF occurrence data OGC API
            fi: Lajitietokeskuksen havaintoaineistojen OGC API -rajapinta
        description:
            en: This portal allows you to query and fetch virva-filtered occurrence data from the repositories of Finnish Biodiversity Information Facility (FinBIF). Latest update 2024-06-25.
            fi: Tämän rajapinnan kautta voit hakea viranomaisrajauksin rajattuja lajitietokeskuksen lajihavaintoja. Päivitetty 2024-06-25.
        keywords:
            en:
                - occurrence
                - geospatial data
                - api
            fi:
                - lajitieto
                - paikkatieto
                - rajapinta
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Luomus
        url: https://laji.fi/
    contact:
        name: Alpo, Turunen
        position: 
            en: Spatial Data Specialist
            fi: Paikkatietoasiantuntija
        address: Pohjoinen Rautatiekatu 13 
        city: Helsinki
        stateorprovince: Uusimaa
        postalcode: FI-00100
        country: 
            en: Finland
            fi: Suomi
        email: alpo.turunen@helsinki.fi
        url: 
            en: https://laji.fi/en
            fi: https://laji.fi/
        role: pointOfContact

resources:

    Birds:
        type: collection
        title: Birds 
        description: This collection contains 8608 occurrences of Birds. 
        keywords:
            en:
                - Birds
                - species
        extents:
            spatial:
                bbox: [19.54434, 59.778728, 30.860287, 70.05583]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-06-09T00:00:00Z
                end: 2024-06-25T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: tmp
                user: tmp
                password: tmp
            id_field: Paikallinen_tunniste
            uri: Havainnon_tunniste
            table: Birds
            geom_field: geometry
            time_field: Keruu_aloitus_pvm
            title_field: Tulkittu_tieteellinen_nimi
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067
