# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: FinBIF occurrence data OGC API
        description:
            en: This portal allows you to query and fetch occurrence data from the repositories of Finnish Biodiversity Information Facility (FinBIF). Currently, this portal includes data specified by virva-authority filters. 
        keywords:
            en:
                - occurrence
                - geospatial data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Luomus
        url: https://laji.fi/
    contact:
        name: Alpo, Turunen
        position: Spatial Data Specialist
        address: Pohjoinen Rautatiekatu 13 
        city: Helsinki
        stateorprovince: Uusimaa
        postalcode: 00100
        country: Finland
        phone: +358 29 412 8819
        email: alpo.turunen@helsinki.fi
        url: https://laji.fi/
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:

    Insects_and_arachnids:
        type: collection
        title: Insects_and_arachnids occurrences
        description: data from lajifi
        keywords:
            en:
                - Insects_and_arachnids
                - species
        extents:
            spatial:
                bbox: [20.8032, 59.8114, 30.19489, 69.29177]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Insects_and_arachnids
            geom_field: geometry

    Fungi_and_lichens:
        type: collection
        title: Fungi_and_lichens occurrences
        description: data from lajifi
        keywords:
            en:
                - Fungi_and_lichens
                - species
        extents:
            spatial:
                bbox: [19.54703, 59.78293, 30.46603, 69.01698]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Fungi_and_lichens
            geom_field: geometry

    Birds:
        type: collection
        title: Birds occurrences
        description: data from lajifi
        keywords:
            en:
                - Birds
                - species
        extents:
            spatial:
                bbox: [19.53695, 59.80844, 30.41057, 69.90905]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Birds
            geom_field: geometry

    Other_organisms:
        type: collection
        title: Other_organisms occurrences
        description: data from lajifi
        keywords:
            en:
                - Other_organisms
                - species
        extents:
            spatial:
                bbox: [21.44, 60.1697, 30.46637, 63.83365]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Other_organisms
            geom_field: geometry

    Molluscs:
        type: collection
        title: Molluscs occurrences
        description: data from lajifi
        keywords:
            en:
                - Molluscs
                - species
        extents:
            spatial:
                bbox: [21.44, 59.81645, 26.83505, 63.59488]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Molluscs
            geom_field: geometry

    Vascular_plants:
        type: collection
        title: Vascular_plants occurrences
        description: data from lajifi
        keywords:
            en:
                - Vascular_plants
                - species
        extents:
            spatial:
                bbox: [19.83214, 59.81239, 29.80941, 68.86395]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Vascular_plants
            geom_field: geometry

    unclassified:
        type: collection
        title: unclassified occurrences
        description: data from lajifi
        keywords:
            en:
                - unclassified
                - species
        extents:
            spatial:
                bbox: [nan, nan, nan, nan]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: unclassified
            geom_field: geometry

    Mammals:
        type: collection
        title: Mammals occurrences
        description: data from lajifi
        keywords:
            en:
                - Mammals
                - species
        extents:
            spatial:
                bbox: [20.67209, 59.81438, 30.19818, 69.3983]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Mammals
            geom_field: geometry

    Bryophytes:
        type: collection
        title: Bryophytes occurrences
        description: data from lajifi
        keywords:
            en:
                - Bryophytes
                - species
        extents:
            spatial:
                bbox: [21.11718, 59.8116, 29.3188, 66.36791]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Bryophytes
            geom_field: geometry

    Fishes:
        type: collection
        title: Fishes occurrences
        description: data from lajifi
        keywords:
            en:
                - Fishes
                - species
        extents:
            spatial:
                bbox: [19.89204, 59.93033, 28.9, 67.78485]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Fishes
            geom_field: geometry

    Myriapods:
        type: collection
        title: Myriapods occurrences
        description: data from lajifi
        keywords:
            en:
                - Myriapods
                - species
        extents:
            spatial:
                bbox: [22.00991, 59.8114, 24.8689, 61.68613]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Myriapods
            geom_field: geometry

    Worms:
        type: collection
        title: Worms occurrences
        description: data from lajifi
        keywords:
            en:
                - Worms
                - species
        extents:
            spatial:
                bbox: [22.35238, 60.1697, 27.16446, 63.64631]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Worms
            geom_field: geometry

    Algae:
        type: collection
        title: Algae occurrences
        description: data from lajifi
        keywords:
            en:
                - Algae
                - species
        extents:
            spatial:
                bbox: [23.63584, 59.93557, 25.79742, 62.25196]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Algae
            geom_field: geometry

    Crustaceans:
        type: collection
        title: Crustaceans occurrences
        description: data from lajifi
        keywords:
            en:
                - Crustaceans
                - species
        extents:
            spatial:
                bbox: [19.88419, 60.10876, 24.93754, 62.52323]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Crustaceans
            geom_field: geometry

    Reptiles_and_amphibians:
        type: collection
        title: Reptiles_and_amphibians occurrences
        description: data from lajifi
        keywords:
            en:
                - Reptiles_and_amphibians
                - species
        extents:
            spatial:
                bbox: [22.33024, 60.06715, 27.58347, 62.81241]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Reptiles_and_amphibians
            geom_field: geometry
