server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fi-FI
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: FinBIF occurrence data OGC API
            fi: Lajitietokeskuksen havaintoaineistojen OGC API -rajapinta
        description:
            en: This portal allows you to query and fetch occurrence data from the repositories of Finnish Biodiversity Information Facility (FinBIF). Currently, this portal includes data specified by virva-authority filters. 
            fi: Tämän rajapinnan kautta voit hakea viranomaisrajauksin rajattuja lajitietokeskuksen lajihavaintoja.
        keywords:
            en:
                - occurrence
                - geospatial data
                - api
            fi:
                - lajitieto
                - paikkatieto
                - rajapinta
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Luomus
        url: https://laji.fi/
    contact:
        name: Alpo, Turunen
        position: 
            en: Spatial Data Specialist
            fi: Paikkatietoasiantuntija
        address: Pohjoinen Rautatiekatu 13 
        city: Helsinki
        stateorprovince: Uusimaa
        postalcode: FI-00100
        country: 
            en: Finland
            fi: Suomi
        phone: +358 29 412 8819
        email: alpo.turunen@helsinki.fi
        url: 
            en: https://laji.fi/en
            fi: https://laji.fi/
        role: pointOfContact

resources:

    Mammals:
        type: collection
        title: Mammals 
        description: occurrences from laji.fi
        keywords:
            en:
                - Mammals
                - species
        extents:
            spatial:
                bbox: [20.819598, 59.813116, 30.326695, 67.808354]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-01-15T00:00:00Z
                end: 2024-04-26T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Mammals
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Birds:
        type: collection
        title: Birds 
        description: occurrences from laji.fi
        keywords:
            en:
                - Birds
                - species
        extents:
            spatial:
                bbox: [19.721958, 59.774893, 30.930585, 69.18262]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-01-15T00:00:00Z
                end: 2024-04-26T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Birds
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Vascular_plants:
        type: collection
        title: Vascular_plants 
        description: occurrences from laji.fi
        keywords:
            en:
                - Vascular_plants
                - species
        extents:
            spatial:
                bbox: [19.94978, 60.131183, 28.170114, 61.198278]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-24T00:00:00Z
                end: 2024-04-25T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Vascular_plants
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Lichenized_and_lichenicolous_fungi:
        type: collection
        title: Lichenized_and_lichenicolous_fungi 
        description: occurrences from laji.fi
        keywords:
            en:
                - Lichenized_and_lichenicolous_fungi
                - species
        extents:
            spatial:
                bbox: [19.88586, 60.10683, 30.46581, 65.92288]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-02-03T00:00:00Z
                end: 2024-04-20T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Lichenized_and_lichenicolous_fungi
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Reptiles_and_amphibians:
        type: collection
        title: Reptiles_and_amphibians 
        description: occurrences from laji.fi
        keywords:
            en:
                - Reptiles_and_amphibians
                - species
        extents:
            spatial:
                bbox: [21.357839, 60.06715, 27.58347, 62.81241]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-02-25T00:00:00Z
                end: 2024-04-19T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Reptiles_and_amphibians
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Moths_and_butterflies:
        type: collection
        title: Moths_and_butterflies 
        description: occurrences from laji.fi
        keywords:
            en:
                - Moths_and_butterflies
                - species
        extents:
            spatial:
                bbox: [21.074811, 60.088405, 25.746484, 62.230013]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-01-31T00:00:00Z
                end: 2024-04-15T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Moths_and_butterflies
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Bryophytes:
        type: collection
        title: Bryophytes 
        description: occurrences from laji.fi
        keywords:
            en:
                - Bryophytes
                - species
        extents:
            spatial:
                bbox: [22.30017, 59.98126, 28.683366, 61.31176]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-06T00:00:00Z
                end: 2024-04-15T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Bryophytes
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Fungi_and_lichens:
        type: collection
        title: Fungi_and_lichens 
        description: occurrences from laji.fi
        keywords:
            en:
                - Fungi_and_lichens
                - species
        extents:
            spatial:
                bbox: [23.595933, 60.212156, 24.679616, 61.940594]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-02-06T00:00:00Z
                end: 2024-04-13T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Fungi_and_lichens
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Macrofungi:
        type: collection
        title: Macrofungi 
        description: occurrences from laji.fi
        keywords:
            en:
                - Macrofungi
                - species
        extents:
            spatial:
                bbox: [22.167362, 60.264261, 25.730559, 67.647971]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-01T00:00:00Z
                end: 2024-04-13T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Macrofungi
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Dragonflies:
        type: collection
        title: Dragonflies 
        description: occurrences from laji.fi
        keywords:
            en:
                - Dragonflies
                - species
        extents:
            spatial:
                bbox: [21.437221, 60.365205, 25.67308, 61.18352]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-28T00:00:00Z
                end: 2024-04-12T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Dragonflies
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Algae:
        type: collection
        title: Algae 
        description: occurrences from laji.fi
        keywords:
            en:
                - Algae
                - species
        extents:
            spatial:
                bbox: [24.714495, 60.107976, 24.75787, 60.14634]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-02-18T00:00:00Z
                end: 2024-04-06T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Algae
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Beetles:
        type: collection
        title: Beetles 
        description: occurrences from laji.fi
        keywords:
            en:
                - Beetles
                - species
        extents:
            spatial:
                bbox: [23.633838, 60.08293, 23.79499, 61.498499]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-26T00:00:00Z
                end: 2024-04-05T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Beetles
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    True_bugs:
        type: collection
        title: True_bugs 
        description: occurrences from laji.fi
        keywords:
            en:
                - True_bugs
                - species
        extents:
            spatial:
                bbox: [28.830795, 61.878581, 28.833966, 61.878987]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-31T00:00:00Z
                end: 2024-03-31T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: True_bugs
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Spiders:
        type: collection
        title: Spiders 
        description: occurrences from laji.fi
        keywords:
            en:
                - Spiders
                - species
        extents:
            spatial:
                bbox: [25.86805, 60.228021, 25.870774, 60.229608]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-30T00:00:00Z
                end: 2024-03-30T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Spiders
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    Fishes:
        type: collection
        title: Fishes 
        description: occurrences from laji.fi
        keywords:
            en:
                - Fishes
                - species
        extents:
            spatial:
                bbox: [23.125441, 59.93033, 27.16449, 63.64631]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-03-02T00:00:00Z
                end: 2024-03-18T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: Fishes
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067

    True_flies:
        type: collection
        title: True_flies 
        description: occurrences from laji.fi
        keywords:
            en:
                - True_flies
                - species
        extents:
            spatial:
                bbox: [29.79728, 62.58345, 29.79728, 62.58345]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2024-02-11T00:00:00Z
                end: 2024-02-11T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: occurrenceID
            table: True_flies
            geom_field: geometry
            time_field: datetimestamp
            title_field: scientificName
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067
