server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
        - fi-FI
    # cors: true
    pretty_print: true
    limit: 10
    templates:
      path: custom/templates/
      static: static/
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: FinBIF occurrence data OGC API
            fi: Lajitietokeskuksen havaintoaineistojen OGC API -rajapinta
        description:
            en: This portal allows you to query and fetch virva-filtered openly available occurrence data from the Finnish Biodiversity Information Facility (FinBIF). Latest update 2024-09-26. 
            fi: Tämän rajapinnan kautta voit hakea viranomaisrajauksin rajattuja avoimesti saatavilla olevia lajitietokeskuksen lajihavaintoja. Päivitetty 2024-09-26.            
        keywords:
            en:
                - occurrence data
                - geospatial data
                - api
            fi:
                - lajitieto
                - paikkatieto
                - rajapinta
        keywords_type: place
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://info.laji.fi/en/frontpage/finnish-biodiversity-information-facility-finbif/terms-of-services/
        properties: 
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Luomus
        url: https://laji.fi/
    contact:
        name: Alpo, Turunen
        position: 
            en: Spatial Data Specialist
            fi: Paikkatietoasiantuntija
        address: Pohjoinen Rautatiekatu 13 
        city: Helsinki
        stateorprovince: Uusimaa
        postalcode: FI-00100
        country: 
            en: Finland
            fi: Suomi
        email: alpo.turunen@helsinki.fi
        url: 
            en: https://laji.fi/en
            fi: https://laji.fi/
        role: pointOfContact

resources:

    ahvenanmaa_points:
        type: collection
        title: ahvenanmaa_points 
        description: 1683 points from the Ahvenanmaa biogeographical area. 
        keywords:
            en:
                - Ahvenanmaa
                - occurrence data
        extents:
            spatial:
                bbox: [19.31766, 59.833332, 21.126104, 60.715543]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 1990-05-01T00:00:00Z
                end: 2024-06-20T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: Paikallinen_tunniste
            uri: Havainnon_tunniste
            table: ahvenanmaa_points
            geom_field: geometry
            time_field: Keruu_aloitus_pvm
            title_field: Suomenkielinen_nimi
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067
    ahvenanmaa_lines:
        type: collection
        title: ahvenanmaa_lines 
        description: 184 lines from the Ahvenanmaa biogeographical area. 
        keywords:
            en:
                - Ahvenanmaa
                - occurrence data
        extents:
            spatial:
                bbox: [19.990032, 60.006174, 20.107237, 60.127607]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 2001-06-03T00:00:00Z
                end: 2016-06-07T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: Paikallinen_tunniste
            uri: Havainnon_tunniste
            table: ahvenanmaa_lines
            geom_field: geometry
            time_field: Keruu_aloitus_pvm
            title_field: Suomenkielinen_nimi
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067
    ahvenanmaa_polygons:
        type: collection
        title: ahvenanmaa_polygons 
        description: 2277 polygons from the Ahvenanmaa biogeographical area. 
        keywords:
            en:
                - Ahvenanmaa
                - occurrence data
        extents:
            spatial:
                bbox: [19.315952, 59.826241, 21.104812, 60.603286]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
            temporal: 
                begin: 1990-01-01T00:00:00Z
                end: 2018-09-02T00:00:00Z
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: Paikallinen_tunniste
            uri: Havainnon_tunniste
            table: ahvenanmaa_polygons
            geom_field: geometry
            time_field: Keruu_aloitus_pvm
            title_field: Suomenkielinen_nimi
            crs:
                - https://www.opengis.net/def/crs/EPSG/0/4326
                - https://www.opengis.net/def/crs/EPSG/0/3067
    occurrence-metadata:
        type: collection
        title: Occurrence Metadata 
        description: This metadata record contains metadata of the all collections in this service 
        keywords:
            en:
                - metadata
                - record
        extents:
            spatial:
                bbox: [19.08317359,59.45414258,31.58672881,70.09229553]
                crs: https://www.opengis.net/def/crs/EPSG/0/3067
            temporal: 
                begin: 1990-01-01T00:00:00Z
                end: 2024-09-26T00:00:00Z
        providers:
          - type: record
            name: TinyDBCatalogue
            data: catalogue.tinydb
            id_field: externalId
            time_field: recordCreated
            title_field: title
    