# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: Alpo's OGC API test with Postgre/PostGIS database
        description:
            en: pygeoapi provides an API to geospatial data
        keywords:
            en:
                - geospatial
                - data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Luomus
        url: https://laji.fi/
    contact:
        name: Alpo, Turunen
        position: Spatial Data Specialist
        address: Pohjoinen Rautatiekatu 13 
        city: Helsinki
        stateorprovince: Uusimaa
        postalcode: 00100
        country: Finland
        phone: +358 29 412 8819
        email: alpo.turunen@helsinki.fi
        url: https://laji.fi/
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    Insects_and_arachnids:
        type: collection
        title: Insects_and_arachnids occurrences
        description: data from lajifi
        keywords:
            en:
                - birds
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Insects_and_arachnids
            geom_field: geometry
            
    Fungi_and_lichens:
        type: collection
        title: Fungi_and_lichens occurrences
        description: data from lajifi
        keywords:
            en:
                - birds
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Fungi_and_lichens
            geom_field: geometry
            
    Birds:
        type: collection
        title: Bird occurrences
        description: data from lajifi
        keywords:
            en:
                - birds
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Birds
            geom_field: geometry

    Other_organisms:
        type: collection
        title: Other_organisms occurrences
        description: data from lajifi
        keywords:
            en:
                - Other_organisms
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Other_organisms
            geom_field: geometry

    Molluscs:
        type: collection
        title: Molluscs occurrences
        description: data from lajifi
        keywords:
            en:
                - Molluscs
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Molluscs
            geom_field: geometry

    Vascular_plants:
        type: collection
        title: Vascular_plants occurrences
        description: data from lajifi
        keywords:
            en:
                - Vascular_plants
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Vascular_plants
            geom_field: geometry

    Mammals:
        type: collection
        title: Mammals occurrences
        description: data from lajifi
        keywords:
            en:
                - Mammals
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Mammals
            geom_field: geometry

    Bryophytes:
        type: collection
        title: Bryophytes occurrences
        description: data from lajifi
        keywords:
            en:
                - Bryophytes
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Bryophytes
            geom_field: geometry

    Fishes:
        type: collection
        title: Fishes occurrences
        description: data from lajifi
        keywords:
            en:
                - Fishes
                - species
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: https://www.opengis.net/def/crs/EPSG/0/4326
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: postgres
                port: 5432
                dbname: my_geospatial_db
                user: postgres
                password: admin123
            id_field: record_id
            table: Fishes
            geom_field: geometry            