from src.app import app, db
from src.models import AdminAPIUser
import click
import secrets


@app.cli.command('add_admin_api_user')
@click.argument('system_id', required=False)
def add_admin_api_user(system_id=None):
    if not system_id:
        system_id = input('Username: ')

    if not system_id:
        raise ValueError('Username is required')

    password = input('Password (leave empty for autogenerated password): ')

    if not password:
        password = secrets.token_urlsafe(48)

    user = AdminAPIUser.query.filter(
        AdminAPIUser.system_id == system_id
    ).first()

    if user is None:
        user = AdminAPIUser(system_id=system_id, password=password)
        db.session.add(user)
        db.session.commit()

        print('Created user {} with password {}'.format(system_id, password))
    else:
        user.password = password
        db.session.commit()

        print('Updated user {} with password {}'.format(system_id, password))
