"""request log

Revision ID: 742825bb9cf5
Revises: 
Create Date: 2024-12-05 11:57:36.973176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742825bb9cf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('api_key_id', sa.String(length=15), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=39), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_log')
    # ### end Alembic commands ###
