"""add api key and admin api user tables

Revision ID: d9b9377cf7d5
Revises: 
Create Date: 2024-09-27 11:33:52.751159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b9377cf7d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_api_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=162), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('key_hash', sa.String(length=162), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key')
    op.drop_table('admin_api_user')
    # ### end Alembic commands ###
