server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
        - fi-FI
    # cors: true
    pretty_print: true
    limit: 10
    templates:
      path: custom/templates
      static: pygeoapi/pygeoapi/static
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: FinBIF occurrence data OGC API
            fi: Lajitietokeskuksen havaintoaineistojen OGC API -rajapinta
        description:
            en: This OGC API - Features allows you to fetch openly available occurrence data from laji.fi. Data is selected using virva filters.
            fi: Tämä OGC API - Features rajapinta mahdollistaa avoimesti saatavilla olevien lajihavaintojen hakemisen laji.fi:stä. Data on virva-rajauksien mukaista.
        keywords:
            en:
                - occurrence data
                - geospatial data
                - api
            fi:
                - lajitieto
                - paikkatieto
                - rajapinta
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://info.laji.fi/en/frontpage/finnish-biodiversity-information-facility-finbif/terms-of-services/
        properties: 
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Luomus
        url: https://laji.fi/
    contact:
        name: Alpo, Turunen
        position: 
            en: Spatial Data Specialist
            fi: Paikkatietoasiantuntija
        address: Pohjoinen Rautatiekatu 13 
        city: Helsinki
        stateorprovince: Uusimaa
        postalcode: FI-00100
        phone: +358 29 412 8819
        fax:
        instructions:
        hours:
        country: 
            en: Finland
            fi: Suomi
        email: alpo.turunen@helsinki.fi
        url: 
            en: https://laji.fi/en
            fi: https://laji.fi/
        role: pointOfContact

resources:
