kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: BRANCH
    required: true
    value: dev
  - name: NAME_PREFIX
    required: false
    value: ""
  - name: HOST_URL
    required: true
  - name: HOST_PATH
    required: true
    value: /
  - name: PYGEOAPI_PORT
    required: true
    value: "5000"
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: pygeoapi-config-${NAME_PREFIX}${BRANCH}
      labels:
        app: pygeoapi-${NAME_PREFIX}${BRANCH}
        version: ${NAME_PREFIX}${BRANCH}
    data:
      catalogue.tinydb: ""
      pygeoapi-config.yml: ""