name: Build Image

on:
  push:
    branches: ['main', 'dev']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-python_scripts
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-pygeoapi
          
    # Build and push the python scripts image
    - name: Buildah Action - python_scripts
      id: build_python_scripts
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}python_scripts
        tags: ${{ steps.meta.outputs.tags }}
        oci: true
        containerfiles: |
          ./Dockerfile
          
    - name: Push python_scripts Image To GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: ${{ steps.build_python_scripts.outputs.tags }}
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}

    # Build and push the pygeoapi image
    - name: Buildah Action - pygeoapi
      id: build_pygeoapi
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}-pygeoapi
        tags: ${{ steps.meta.outputs.tags }}
        oci: true
        containerfiles: |
          ./pygeoapi/Dockerfile
          
    - name: Push pygeoapi Image To GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: ${{ steps.build_pygeoapi.outputs.tags }}
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}