name: Build Image

on:
  push:
    branches: ['main', 'dev']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-push-images:
    strategy:
      matrix:
        configuration: [ {name: python-scripts, dockerfile: Dockerfile, target: ''}, {name: pygeoapi-default, dockerfile: pygeoapi/Dockerfile, target: 'default'}, {name: pygeoapi-virva, dockerfile: pygeoapi/Dockerfile, target: 'virva'} ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.configuration.name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.configuration.dockerfile }}
          build-args: |
            target=${{ matrix.configuration.target }}
